version: "3.1"
services:
  core:
    build: .
    command: bash -c "npm start"
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - .:/core
