version: "3.1"
services:
  api:
    container_name: pay-api
    restart: always
    build:
      context: ./api
    command: "yarn start"
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./api:/api
      - /api/node_modules
    networks:
      - pay_network
  app:
    container_name: pay-app
    build:
      context: ./app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "80:80"
    networks:
      - pay_network
networks:
  pay_network:
    driver: bridge
